version: "3"

services:

  # webserver to handle all traffic to bety/pecan/rabbitmq
  traefik:
    image: traefik:latest
    networks:
      - pecan
    command: --api --web --docker --docker.domain=traefik --logLevel=INFO #--docker.exposedbydefault=false
    ports:
      - "8000:80"     # The HTTP port
      - "8001:8080" # The Web UI (enabled by --api)
    volumes:
      - /dev/null:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  # postgresql + postgis to hold all the data
  postgres:
    image: mdillon/postgis:9.5
    networks:
      - pecan
    #ports:
    #  - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]

  # rabbitmq to connect to extractors
  rabbitmq:
    image: rabbitmq:management
    networks:
      - pecan
    #ports:
      #- 5672
      #- 15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.port=15672"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend=rabbitmq"
    restart: unless-stopped
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == worker]

  # BETY rails frontend to the database
  bety:
    image: pecan/bety:unicorn
    networks:
      - pecan
    #ports:
      #- 8000
    environment:
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=1208q7493e8wfhdsohfo9ewhrfiouaho908ruq30oiewfdjspadosuf08q345uwrasdy98t7q243
      - RAILS_RELATIVE_URL_ROOT=/bety
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/bety/"
      - "traefik.backend=bety"
    restart: unless-stopped
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]

  # PEcAn web front end, this is just the PHP code
  pecan-gui:
    image: pecan/pecan-web
    networks:
      - pecan
    #ports:
      #- 80
    volumes:
      - pecan:/data
      - ${PWD}/web:/var/www/html/pecan
    depends_on:
       - postgres
       - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefix:/pecan/"
      - "traefik.backend=pecan"
    restart: unless-stopped
    deploy:
      mode: replicated
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]

networks:
  pecan:

volumes:
  postgres:
  rabbitmq:
  pecan:
