# mkdir -p volumes/{lib,pecan,portainer,postgres,rabbitmq,traefik}
# 
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml

version: '3'

services:
  web:
    volumes:
      - '${PWD}/web:/var/www/html/pecan'
      - '${PWD}/docker/web/config.docker.php:/var/www/html/pecan/config.php'

  # executor can compile the code
  executor:
    volumes:
      - '${PWD}:/pecan/'
      - '${PWD}/volumes/lib:/usr/local/lib/R/site-library/'

  # use same for R development in rstudio
  rstudio:
    volumes:
      - '${PWD}:/pecan/'
      - '${PWD}:/home/carya/pecan/'
      - '${PWD}/volumes/lib:/usr/local/lib/R/site-library/'

  # use following as template for other models
  # this can be used if you are changng the code for a model in PEcAN
  sipnet:
    volumes:
      - '${PWD}/volumes/lib:/usr/local/lib/R/site-library/'    

  # this will open postgres to the hostcompute
  #postgres:
  #  ports:
  #    - '5432:5432'

  # Allow to see all docker containers running, restart and see log files.
  #portainer:
  #  image: portainer/portainer:latest
  #  command:
  #    - --admin-password=${PORTAINER_PASSWORD:-}
  #    - --host=unix:///var/run/docker.sock
  #  restart: unless-stopped
  #  networks:
  #    - pecan
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.backend=portainer"
  #    - "traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE:-}PathPrefixStrip: /portainer"
  #    - "traefik.website.frontend.whiteList.sourceRange=${TRAEFIK_IPFILTER:-172.16.0.0/12}"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer:/data

volumes:
  traefik:
    driver_opts:
      type: none
      device: '${PWD}/volumes/traefik'
      o: bind
  postgres:
    driver_opts:
      type: none
      device: '${PWD}/volumes/postgres'
      o: bind
  rabbitmq:
    driver_opts:
      type: none
      device: '${PWD}/volumes/rabbitmq'
      o: bind
  pecan:
    driver_opts:
      type: none
      device: '${PWD}/volumes/pecan'
      o: bind
  portainer:
    driver_opts:
      type: none
      device: '${PWD}/volumes/portainer'
      o: bind
