# This is a basic workflow to help you get started with Actions

name: book

on:
  push:
    branches: master
  pull_request:
    branches: master 


jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    container: pecan/depends:develop

    
    steps:
    
    - uses: actions/checkout@v2
    - name: installing dependencies
      run : |
          apt-get update \
          && apt-get -y --no-install-recommends install \
          jags \
          time \
          libgdal-dev \
          libglpk-dev \
          librdf0-dev \
          libnetcdf-dev \
          libudunits2-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev

    # Building book from source using makefile
    - name: Building book
      run: cd book_source && make
      
    - name: looking for generated html  
      run: cd _book

    - name: Commiting the changes to pecan documentation repo
      run: |
        git init 
        git add .
        git commit -m "documentation updated by actions"
        git remote add origin https://github.com/MukulMaheshwari/pecan-documentation.git
        git push -u origin master
        
