name: renderbook

on:
  push:
    branches:
      - master
      - develop

    tags:
      - '*'

  pull_request:

jobs:
bookdown:
  name: Render-Book
    runs-on: ubuntu-latest  

    container: 
      image: pecan/depends:R${{ matrix.R }}

    steps:
    # checkout source code
    - uses: actions/checkout@v2
    # install rmarkdown
    - name: Install rmarkdown
      run: |
        Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
    # compile PEcAn code
    - name: build
      run: make -j1
    # render book
    - name: Render Book
      run: |
        cd book_source
        Rscript -e 'options(bookdown.render.file_scope=FALSE); bookdown::render_book("index.Rmd", "bookdown::gitbook")'
    # save artifact
    - uses: actions/upload-artifact@v2
      with:
        name: pecan-documentation
        path: book_source/_book/
    # download documentation repo
    - name: Checkout documentation repo
      if: github.event_name != 'pull_request'
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/pecan-documentation
        path: pecan-documentation
        token: ${{ secrets.GH_PAT }}
    # upload new documentation
    - name: publish to github
      if: github.event_name != 'pull_request'
      run: |
        export VERSION=${GITHUB_REF##*/}
        cd pecan-documentation && mkdir -p $VERSION
        git config --global user.email "pecanproj@gmail.com"
        git config --global user.name "GitHub Documentation Robot"
        rsync -a --delete ../_book/ $VERSION
        git add --all *
        git commit -m "Build book from pecan revision $GITHUB_SHA" || true
        git push -q origin master
